version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: ["npm", "run", "serve"]